"""empty message

Revision ID: ede73cf4aaa9
Revises: 
Create Date: 2023-01-05 19:39:41.411176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ede73cf4aaa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_delays_USA')
    op.drop_table('flight_cancelations_USA')
    op.drop_table('flight_cancelations_WW')
    op.drop_table('flight_delays_WW')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_delays_WW',
    sa.Column('number_of_delays_ww', sa.INTEGER(), server_default=sa.text('nextval(\'"flight_delays_WW_number_of_delays_ww_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('day_recorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number_of_delays_ww', name='flight_delays_WW_pkey')
    )
    op.create_table('flight_cancelations_WW',
    sa.Column('number_of_cancelations_ww', sa.INTEGER(), server_default=sa.text('nextval(\'"flight_cancelations_WW_number_of_cancelations_ww_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('day_recorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number_of_cancelations_ww', name='flight_cancelations_WW_pkey')
    )
    op.create_table('flight_cancelations_USA',
    sa.Column('number_of_cancelations_usa', sa.INTEGER(), server_default=sa.text('nextval(\'"flight_cancelations_USA_number_of_cancelations_usa_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('day_recorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number_of_cancelations_usa', name='flight_cancelations_USA_pkey')
    )
    op.create_table('flight_delays_USA',
    sa.Column('number_of_delays', sa.INTEGER(), server_default=sa.text('nextval(\'"flight_delays_USA_number_of_delays_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('day_recorded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number_of_delays', name='flight_delays_USA_pkey')
    )
    # ### end Alembic commands ###
